/**
 * Transcript file management
 */

import fs from "fs";
import { TranscriptEntry } from "./types.js";

export class TranscriptManager {
  private outfile: string;
  private version?: string;

  constructor(outfile: string, version?: string) {
    this.outfile = outfile;
    this.version = version;
  }

  /**
   * Initialize the transcript file with a header if it doesn't exist
   */
  initialize(): void {
    if (!fs.existsSync(this.outfile)) {
      const now = new Date().toISOString().replace("T", " ").split(".")[0];
      const versionInfo = this.version ? `\n_Generated by audio-transcription-mcp v${this.version}_\n` : "";
      const header = `# Meeting Transcript\n${versionInfo}_Started: ${now}_\n\n---\n\n`;
      fs.writeFileSync(this.outfile, header, "utf8");
    }
  }

  /**
   * Append a transcript entry to the file
   */
  append(entry: TranscriptEntry): void {
    const line = `\n**${entry.timestamp}**  ${entry.text}\n`;
    fs.appendFileSync(this.outfile, line, "utf8");
  }

  /**
   * Append a system notification to the transcript (e.g., pause/resume)
   */
  appendSystemMessage(message: string): void {
    const now = new Date();
    const timestamp = now.toISOString().replace("T", " ").split(".")[0];
    const line = `\n---\n**${timestamp}** _[SYSTEM]_ ${message}\n---\n\n`;
    fs.appendFileSync(this.outfile, line, "utf8");
  }

  /**
   * Get the full transcript content
   */
  getContent(): string {
    if (!fs.existsSync(this.outfile)) {
      return "";
    }
    return fs.readFileSync(this.outfile, "utf8");
  }

  /**
   * Clear the transcript file
   */
  clear(): void {
    if (fs.existsSync(this.outfile)) {
      fs.unlinkSync(this.outfile);
    }
    this.initialize();
  }

  /**
   * Delete the transcript file completely (no reinitialization)
   */
  delete(): void {
    if (fs.existsSync(this.outfile)) {
      fs.unlinkSync(this.outfile);
    }
  }

  /**
   * Get file path
   */
  getFilePath(): string {
    return this.outfile;
  }
}

